name: Build and Deploy
on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - master
  workflow_dispatch:
jobs:
  build:
    name: Build, Test, Deploy and Cover .NET Core
    runs-on: ubuntu-latest
    env:
      COMMIT_SHA: ${{ github.sha }}
    steps:
      - uses: actions/checkout@v3

      - name: Setup dotnet 3.1
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '3.1.x'

      - name: Display dotnet version
        run: dotnet --version

      - name: Restore
        run: dotnet restore src/PockyBot.NET.sln

      - name: Build
        run: dotnet build src/PockyBot.NET/PockyBot.NET.csproj

      - name: Test
        run: dotnet test src/PockyBot.NET.Tests/PockyBot.NET.Tests.csproj

      - uses: actions/upload-artifact@v2
        with:
          name: codecov
          path: src/PockyBot.NET.Tests/coverage.opencover.xml

      - name: Run coverage script
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        if: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}
        run: chmod +x ./cover.sh && ./cover.sh

      - name: Setup Node.js environment
        if: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}
        uses: actions/setup-node@v3.5.1
        with:
          node-version: 10.18.x
      - name: Display node version
        if: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}
        run: node --version
      - name: Run deploy script
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        if: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}
        run: chmod +x ./deploy.sh && ./deploy.sh
