name: Build and Deploy
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
jobs:
  build:
    name: Build and Test .NET Core
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup dotnet 3.1
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '3.1.x'
      - name: Display dotnet version
        run: dotnet --version
      - name: Restore
        run: dotnet restore src/PockyBot.NET.sln
      - name: Build
        run: dotnet build src/PockyBot.NET/PockyBot.NET.csproj
      - name: Test
        run: dotnet test src/PockyBot.NET.Tests/PockyBot.NET.Tests.csproj
      - name: Run coverage script
        run: chmod +x ./cover.sh && ./cover.sh
      - name: Install node js
        run: nvm install 10.18
      - name: Display node version
        run: node --version
      - name: Run deploy script
        run: chmod +x ./deploy.sh && ./deploy.sh ${{ secrets.NUGET_API_KEY }}
